### ISSUE TITLE
코드 확인 이슈

### ISSUE THREAD

**Issue by HerJoon** [go-tiger/chicken-project_team2#55]
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/mypage.routes.js#L12
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/util/multer.js#L12

주석 마저 없에주시면 됩니다. 

https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/mycart.routes.js#L29
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/mycart.routes.js#L45
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/mypage.routes.js#L21
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/mypage.routes.js#L52
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/menu.routes.js#L17
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/user.routes.js#L108
https://github.com/go-tiger/chicken-project_team2/blob/f4b8cf3377c91a784ca69f8baffa49a4663e945e/routes/user.routes.js#L119

error 처리를 다 마저 해주셨으면 좋을것  같습니다.

**Comment by go-tiger** [comment]
이슈내용 반영
